Create auth header  and file images
GSG-CF04/FoodApp-7 pull request #21
Opened 2021-10-24 19:03 UTC by techhana2014

this is only the figure of header

2021-10-24 19:36 UTC, A7medhq approved these changes
Great Job

2021-10-25 06:18 UTC, yaqootturman requested changes

2021-10-25 06:18 UTC, yaqootturman commented on Auth/auth.html
> +		<img src="assets/imgs/Auth/image-000.png"  >
the image is not appear, try to add '/' before assest, to make it:
``` <img src="/assets/imgs/Auth/image-000.png"  >```

2021-10-25 06:18 UTC, yaqootturman commented on Auth/auth.html
> +	<div  class="imagheader">
make class name as camelCase 
imgHeader

2021-10-25 13:17 UTC, kakashii7 approved these changes

2021-10-28 07:28 UTC, closed without merging